module-build/tsconfig.esm.json, module-build/tsconfig.json, packages/dockview/src/__tests__/dockview/dockviewComponent.spec.ts, packages/dockview/src/dockview/dockviewComponent.ts
caching layer is not required, just read panels directly from the group
models
=> feat: remove panels caching layer

packages/dockview-core/src/__tests__/dockview/dockviewComponent.spec.ts, packages/dockview-core/src/dockview/dockviewComponent.ts
external-dnd events should not trigger the top-level center drop target
=> bug: external-dnd event regression

.codesandbox/ci.json, packages/dockview-core/src/dockview/dockviewGroupPanel.ts, packages/dockview-core/src/dockview/dockviewGroupPanelModel.ts, packages/docs/docs/components/dockview.mdx, packages/docs/sandboxes/lockedgroup-dockview/package.json, packages/docs/sandboxes/lockedgroup-dockview/public/index.html, packages/docs/sandboxes/lockedgroup-dockview/src/app.tsx, packages/docs/sandboxes/lockedgroup-dockview/src/index.tsx, packages/docs/sandboxes/lockedgroup-dockview/src/styles.css, packages/docs/sandboxes/lockedgroup-dockview/tsconfig.json
In my application, I have groups that are locked, and when dragging panels over them, the drop target overlay is shown. This, in my case, sometimes makes the UX feel a bit confusing as to what is possible with the placement of the panels. Mostly the confusion comes when I have a panel inside a locked group with a component that has a dropable area for other things than panels.
My solution is to make the `locked` property assignable to `no-drop-target`.
@mathuo what do you think?
=> feat: added the option for 'no-drop-target' for locked on dockview groups

packages/docs/docs/components/dockview.mdx
Removes unsupported option supressClosable from docs
=> Remove supressClosable option from docs

packages/dockview-core/src/splitview/splitview.scss
Hi,
If the `sash` class is disabled, it seems more correct not to show `background-color` on hover.
=> Remove the hover effect for inactive sash classes.

packages/dockview-core/src/api/component.api.ts, packages/dockview-core/src/dockview/dockviewComponent.ts, packages/dockview-core/src/dockview/dockviewPopoutGroupPanel.ts, packages/dockview-core/src/popoutWindow.ts
[[Copy of original PR](https://github.com/mathuo/dockview/pull/467); changed target from master to 469-add-window-lifecycle-callbacks]
This PR adds the ability for users to tap into window-lifecycle events associated with groups that are popped-out or popped-in. Specifically, the PR makes changes such that the user can provide handlers for when a window has opened, and when a window is about to close.
This is particularly useful when the user needs to get a handle to the Window object of the popped-out window.
=> Add window-lifecycle callbacks

packages/dockview-core/src/dockview/dockviewComponent.ts
Width and height were swapped when calling layout for floating panels. This sometimes resulted in swapped width and height info from the API after resizing or moving floating panels (first is width, second is height in the image):
This PR fixes the bug.
=> Set width and height correctly when calling layout for floating panels

packages/dockview-core/src/dockview/dockviewComponent.scss
Quick attempt to fix. I think it works but need to confirm, applies the CSS to the "tab-group" which sits in a split-view view element rather than applying it to the view element directly
=> bug: --group-gap-size overflow fix

packages/dockview-core/src/__tests__/dnd/overlay.spec.ts, packages/dockview-core/src/api/component.api.ts, packages/dockview-core/src/constants.ts, packages/dockview-core/src/dnd/overlay.ts, packages/dockview-core/src/dockview/dockviewComponent.ts, packages/dockview-core/src/dockview/dockviewFloatingGroupPanel.ts, packages/dockview-core/src/dockview/options.ts, packages/dockview-core/src/types.ts, packages/docs/docs/core/panels/add.mdx, packages/docs/sandboxes/react/dockview/demo-dockview/src/groupActions.tsx, packages/docs/sandboxes/react/dockview/demo-dockview/src/panelActions.tsx, packages/docs/sandboxes/react/dockview/floating-groups/src/app.tsx, packages/docs/src/generated/api.output.json, packages/docs/templates/dockview/demo-dockview/react/src/defaultLayout.ts, packages/docs/templates/dockview/demo-dockview/react/src/groupActions.tsx, packages/docs/templates/dockview/demo-dockview/react/src/panelActions.tsx, packages/docs/templates/dockview/floating-groups/react/src/app.tsx, packages/docs/templates/dockview/floating-groups/vue/src/index.ts
Work done:
- Closes https://github.com/mathuo/dockview/issues/544
- New argument `options.position` for floating groups, just like for popout groups, that supports the full range of left/right/width and top/bottom/height settings of CSS absolute positioning
- Drag n Drop and Resizing of floating groups "anchors" the group to the nearest corner. (E.g. If user moves a floating window near the bottom right, it will follow bottom right if window is resized, and same for all 4 corners)
- Added relevant tests
- Updated docs
See Loom video for demo:
https://www.loom.com/share/5b24d26a68ea47548986c379156b9450?sid=104d2e26-41c5-40e5-9b53-534b1b5d346a
=> Allow right and bottom anchored floating groups

packages/dockview-core/src/dockview/dockviewComponent.ts
seems like they should be passed through here
correct me if I'm wrong
=> bug: fix passing through options for opening single panel in a popot window

packages/dockview-core/src/splitview/splitview.ts
If there are hidden views, the calculated heights will not be aligned.
=> fix: splitview layout view size with hidden view

packages/dockview-core/src/overlay/overlay.ts, packages/dockview-core/src/overlay/overlayRenderContainer.ts, packages/dockview-core/src/theme.scss
Replaced const with css variable `--dv-floating-z-index` to easily override. Related to #720
=> Added support for custom overlay z-index

packages/dockview/README.md
This will hopefully make the image show up on the npm page
=> docs: add the splash-screen to the dockview package

packages/dockview-core/src/dockview/dockviewComponent.ts
The initial `onDidDimensionsChange` event is fired with `{ width: 0, height: 0}` without the initial set size and the `resize` event still referenced the parent widow's sizing.
=> 🐛 fix: set initial size and use proper window on event

packages/dockview-core/src/dockview/dockviewComponent.ts
I created [this issue](https://github.com/mathuo/dockview/issues/777) earlier.
After a lot of digging, with these changes I was able to get the behaviour I needed from Dockview. I can't seem to think of a viable reason why you would ever not want to have at least one group showing? At least not for my use cases.
The watermark still shows when there are no tabs - so I'm not sure if there's a technical reason that I'm not thinking about.
I've patched these changes into my project and all seems to be working perfectly.
=> Do not close groups if they're the only group

packages/docs/sandboxes/react/dockview/demo-dockview/src/app.tsx, packages/docs/templates/dockview/demo-dockview/react/src/app.tsx
Currently, the Dockview-Demo on CodeSandbox looks like this:
As far as I can tell, This seems to be because strict mode causes the Dockview to load, unload, then load again, which causes onReady to be called twice, which causes DefaultLayout to be called twice, which puts two copies of the default layout into state. (Groups state & Panels state)
As I see it, there are a few possible solutions here:
1. Dockview could be changed to call each onDidRemoveGroup and onDidRemovePanel hook while unloading, causing Group and Panel state to update naturally in their associated hooks.
2. Dockview could expose an onWillUnload hook, mirror to the onReady hook, that gets called when Dockview starts unloading. Then, state resets could be placed in there.
3. You can just place your state resets in …
=> Fixing duplicate state in React-Dockview-Demo caused by strict mode

packages/dockview-core/src/dockview/components/titlebar/tabsContainer.ts
Check to ensure `tabToRemove` is not undefined before accessing, which appears to be the case when navigating away from/unmounting dockview with a popout open.
=> check tabToRemove is not undefined before access

packages/dockview-core/src/dockview/dockviewComponent.ts
Make `id` option when calling `props.containerApi.addGroup({id:'customID', direction: 'within' });` work.
Issue: https://github.com/mathuo/dockview/issues/676
=> Make `id` option in addGroup without referenceGroup/referencePanel work

README.md
npm on the package page now adds some prefix/suffix to IDs generated from markdown headers, therefore the link in the repo README wasn't scrolling the page to the Provenance section when clicked, but that was obviously an intention
this PR fixes the link
=> Fix provenance npm link

packages/dockview-core/src/api/component.api.ts, packages/dockview-core/src/dockview/dockviewComponent.ts, packages/docs/sandboxes/react/dockview/popout-group/src/app.tsx
This is attempt to add an event that gets triggered if the popout you attempt to open gets blocked by the browser, so you can inform the user about that they need to allow popups.
https://github.com/mathuo/dockview/issues/896
=> [896] Add onDidBlockPopout event

packages/dockview-core/src/__tests__/dockview/dockviewComponent.spec.ts, packages/dockview-core/src/dockview/components/titlebar/tabs.ts, packages/dockview-core/src/dockview/dockviewComponent.ts
If you restore a stored layout from JSON that includes a popout on page load, most browser will block it from opening since the user didn't initiate opening the new popup window. Currently it is hard to determine if this happens and to handle it so that pop out content isn't lost.
This adds an event that triggers if the popout fails to open because of window.open failing to return a window object (most likely blocked by browsers popup blocker) and it also adds the popout group back into grid in the same way as if you would have closed the popout window manually. Hopefully this makes sense.
This is my suggestion for how to improve the behaviour when the browsers blocks the popout from opening and I'm happy to create some settings/props to make it optional.
=> [896] Restore Popout content for blocked popouts and emit onDidBlockPopout event
